on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: The tag name
      prerelease:
        type: boolean
        description: Pre-release
      message:
        required: true
        description: Release message

name: Build and create Release

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build .deb file
        id: build_deb
        run: |
          bash make_deb.sh
          mv deb.deb geofetch.deb
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.tag_name }}
          body: |
            Download the source .zip file and check README.md for instructions on how to install.
            ${{ github.event.inputs.message }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          artifacts: |
            geofetch.deb
